// Generated by CoffeeScript 1.7.1
var buffer, content, e, fs, generatedCode, infile, injector, outfile, program, _ref;

program = require('commander');

fs = require('fs');

injector = require('./angular-injector');

program.version(require('../package.json').version).usage('<infile> <outfile>').option('-t, --token', 'Token function to inject', 'ng').parse(process.argv);

if (program.args.length !== 0 && program.args.length !== 2) {
  console.error('angular-injector should be called with an input and output file, or no arguments if using stdio');
  process.exit(1);
}

if (program.args.length === 2) {
  _ref = program.args, infile = _ref[0], outfile = _ref[1];
  try {
    content = fs.readFileSync(infile, 'utf-8');
  } catch (_error) {
    e = _error;
    console.error('Error opening: ' + infile);
    process.exit(1);
  }
  generatedCode = injector.annotate(content, program);
  try {
    fs.writeFileSync(outfile, generatedCode);
  } catch (_error) {
    e = _error;
    console.error('Error writing to: ' + outfile);
    process.exit(1);
  }
} else {
  buffer = '';
  process.stdin.setEncoding('utf8');
  process.stdin.resume();
  process.stdin.on('data', function(chunk) {
    return buffer += chunk;
  });
  process.stdin.on('end', function() {
    return process.stdout.write(injector.annotate(buffer, program));
  });
}
